[profile.default]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 1_000 # 1000
via_ir = true

src = "src"
out = "out"
libs = ["lib"]


[invariant]
runs = 20 # 2000
depth = 3 # 25
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[rpc_endpoints]
base = "${BASE_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
